Перейти на FrozenDictionary в Structure.
Stepami/hydrascript pull request #83
Opened 2024-08-10 08:53 UTC by FoxTes

Закрывает https://github.com/Stepami/hydrascript/issues/81

2024-08-10 11:57 UTC, Stepami requested changes
Также, необходимо написать комментарий
```
I have read the CLA Document and I hereby sign the CLA
```
Согласно https://github.com/Stepami/hydrascript/pull/83#issuecomment-2280421551

2024-08-10 11:57 UTC, Stepami commented on src/Domain/HydraScript.Domain.FrontEnd/Lexer/Impl/Structure.cs
> +        ((IEnumerable<TokenType>)Types.Values).GetEnumerator();
Предлагаю сделать без явного приведения:
```cs
// ReSharper disable once NotDisposedResourceIsReturned
public IEnumerator<TokenType> GetEnumerator() =>
    Types.Values.AsEnumerable().GetEnumerator();
```

2024-08-11 08:07 UTC, Stepami commented
> Также, необходимо написать комментарий
> 
> ```
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> ```
> 
> Согласно https://github.com/Stepami/hydrascript/pull/83#issuecomment-2280421551

@FoxTes имеется ввиду комментарий к PR, а не к коммиту 

Вот пример: https://github.com/Stepami/hydrascript/pull/65#issuecomment-2250394348

2024-08-11 08:33 UTC, Stepami approved these changes
👍

2024-08-11 08:46 UTC, FoxTes commented
I have read the CLA Document and I hereby sign the CLA

2024-08-11 10:52 UTC, merged

2024-08-11 10:54 UTC, Stepami commented
@FoxTes Спасибо! Отличная работа!